NBIZ-864 NGII: Webcomponent concepten uitbreiden met letterbalk
dotwebstack/dotwebstack-webcomponents pull request #54
Opened 2020-11-26 12:25 UTC by jrdegroot

2020-11-26 12:33 UTC, bmklaijkadaster approved these changes

2020-11-26 12:33 UTC, bmklaijkadaster commented on docs/api.md
> +based on the first letter of the provided `field`
```suggestion
based on the first letter of the provided `field`.
```

2020-11-26 12:33 UTC, bmklaijkadaster commented on src/components/LetterBarFilter.tsx
> +  const items = ['0-9', ...[...Array(26).keys()].map(i => String.fromCharCode(i + 97)),
Redelijk magic, kan je niet 'abcdefghijklmnopqrstuvwxyz'.toCharArray() doen oid?

2020-11-26 12:33 UTC, bmklaijkadaster commented on src/i18n.ts
> +          showAll: 'toon alles',
De rest is met hoofdletters... 
```suggestion
          showAll: 'Toon alles',
```

2020-11-26 12:33 UTC, bmklaijkadaster commented on src/i18n.ts
> +          showAll: 'show all',
```suggestion
          showAll: 'Show all',
```

2020-11-26 13:29 UTC, jrdegroot commented on src/i18n.ts
> +          showAll: 'toon alles',
![image](https://user-images.githubusercontent.com/4056615/100356587-b8dd4780-2ff3-11eb-9a98-c5a147873856.png)
dat is bewust, omdat de tekst in de balk wordt gebruikt.

2020-11-27 16:04 UTC, pmaria requested changes

2020-11-27 16:04 UTC, pmaria commented on src/components/TupleList.tsx
> +      return !filterByStartOfSearchString && value.includes(searchString!.toLowerCase());
Als je `searchString` een param maakt, dan heb je die bang operator niet nodig. Idem hieronder.

2020-11-27 16:04 UTC, pmaria commented on src/components/TupleList.tsx
>    getSearchResults = () => {
de logic van deze function is nu wel lastig te volgen. 
Volgens mij wordt het makkelijker te volgen als je de twee search cases van elkaar scheidt. Dan heb je minder compacte code, maar wel makkelijker te begrijpen.

2020-12-01 09:47 UTC, jrdegroot commented on tsconfig.json
> +    "downlevelIteration": true,
Die was nodig voor de obscure a-z generation :D

2020-12-01 09:53 UTC, jrdegroot commented on src/components/TupleList.tsx
>    getSearchResults = () => {
Dit was ook eerst mijn plan, maar getBindingSets is het punt waar het al fout gaat. Daar wordt gesorteerd, gefilterd (op basis van pagination) en dus gefilterd op basis van een search string. Om die reden had ik al bewust 2 inner functions gemaakt om duidelijk te maken waar op wordt gefilterd, first letter of contains (dus bij een gewone search)

2020-12-01 10:11 UTC, jrdegroot commented on src/components/TupleList.tsx
> +      return !filterByStartOfSearchString && value.includes(searchString!.toLowerCase());
Mee eens, alleen dan loop je weer tegen een issue aan op regel 62.... Zoals ik al eerder aangaf. De basis van de TupleList is niet heel sterk

 const length = this.props.search ? **this.filterResults()**.length : this.props.result.getBindingSets().length;

2020-12-02 07:29 UTC, pmaria approved these changes

2020-12-02 09:59 UTC, merged