[DRAFT] Concise bounded description
dotwebstack/dotwebstack-webcomponents pull request #56
Opened 2020-12-06 15:20 UTC by louwev

**Branched off of #53 - so the diff here includes those changes**

2020-12-10 17:15 UTC, jrdegroot requested changes

2020-12-10 17:15 UTC, jrdegroot commented on src/components/ConciseBoundedDescription.tsx
> +      {effectiveInformationResource ? (
zelf gebruik ik hier liever 

{effectiveInformationResource && (
        < InformationResource resource={effectiveInformationResource} />
      )}

null renderen is vaag, met && is het falsy en wordt er helemaal niets mee gedaan

2020-12-10 17:15 UTC, jrdegroot commented on src/components/InlineResource.tsx
> +            {isLast(index) ? null : ' • '}
is hier ook geen specifieke html char voor?

2020-12-10 17:15 UTC, jrdegroot commented on src/components/Resource.tsx
> +      <Fragment key={index}>
Waarom hier Fragment als je een regel erboven wel de korte versie <> gebruikt?

2020-12-10 17:15 UTC, jrdegroot commented on src/components/Resource.tsx
> +        {appendBreak ? <br /> : null}
{appendBreak && <br/>}

2020-12-10 17:15 UTC, jrdegroot commented on src/components/Resource.tsx
> +          {resourceType ? (
&&

2020-12-10 17:15 UTC, jrdegroot commented on src/i18n.ts
> +          primaryTopicType: 'Primair onderwerp',
Niet echt B1, ik zou hier denk ik voor hoofdonderwerp ofzo kiezen

2020-12-10 17:15 UTC, jrdegroot commented on src/i18n.ts
> +          persistentUri: 'Persistente URI',
Wat is een Persistente URI?

2020-12-10 22:04 UTC, louwev commented on src/components/Resource.tsx
> +      <Fragment key={index}>
`< key={index}>` werkt niet, anders had ik idd de korte versie gebruikt

2020-12-10 22:05 UTC, louwev commented on src/components/InlineResource.tsx
> +            {isLast(index) ? null : ' • '}
dat blijkt `&bull;` te zijn, aangepast

2020-12-10 22:17 UTC, louwev commented on src/components/ConciseBoundedDescription.tsx
> +type ResourceProps = {
het ging er hier eigenlijk om dat je in de "echte" resource props een eigenschap hebt `resourceIri`, die aangeeft over welke resource het moet gaan. De `ResourceProps` die je hier kan doorgeven aan `ConciseBoundaryDescription`  mag die prop niet bevatten

2020-12-10 22:23 UTC, louwev commented on src/i18n.ts
> +          persistentUri: 'Persistente URI',
https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/document/10-rules-persistent-uris
maarja misschien moet dit label configurabel en optioneel worden

2020-12-11 17:57 UTC, pmaria approved these changes

2020-12-15 07:19 UTC, jrdegroot approved these changes

2020-12-15 08:04 UTC, merged